#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PI 3.14159265359f
#define EPS 1e-3f

#define WINDOW_NAME "pseudo-3d"

#define DEFAULT_SCREEN_WIDTH 640
#define DEFAULT_SCREEN_HEIGHT 640 //It needs to be in config
#define TEXTURE_SIZE 64
#define WORLD_TEXTURE_SCALE 40
#define DEFAULT_FOV PI / 3

#define EDITOR_SCREEN_SELECT_RADIUS 10
#define EDITOR_ZOOM_STEP 1.0f
#define EDITOR_DEFAULT_MAX_ZOOM 180
#define EDITOR_DEFAULT_MIN_ZOOM 16

#endif
